// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// logic_in //
// -------- //

#define logic_in_wrap_target 0
#define logic_in_wrap 2

static const uint16_t logic_in_program_instructions[] = {
            //     .wrap_target
    0xe080, //  0: set    pindirs, 0                 
    0x4001, //  1: in     pins, 1                    
    0x0001, //  2: jmp    1                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program logic_in_program = {
    .instructions = logic_in_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config logic_in_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + logic_in_wrap_target, offset + logic_in_wrap);
    return c;
}
#endif

